Graceful fail on pipeline not found - now with tests
Parsagon/parsagon-python pull request #5
Opened 2023-06-22 22:45 UTC by montaguegabe

Continuation of #2

2023-06-23 11:20 UTC, Sand1929 requested changes

2023-06-23 11:20 UTC, Sand1929 commented on src/parsagon/api.py
> +            if isinstance(error_value, dict) and error_value.get("detail") == "Not found.":
Seems like APIException should include data about status codes, which would make this check simpler

2023-06-23 11:20 UTC, Sand1929 commented on src/parsagon/api.py
> +        return self
why does this return self?

2023-06-23 14:56 UTC, montaguegabe commented on src/parsagon/exceptions.py
> +    def to_string(self, verbose):
It’s not used right now, but I think in the future we might want to give different levels of info about exceptions depending on whether the command was run with -v

2023-06-23 14:56 UTC, montaguegabe commented on src/parsagon/api.py
> +            if isinstance(error_value, dict) and error_value.get("detail") == "Not found.":
Ah yes good idea

2023-06-23 15:02 UTC, montaguegabe commented on src/parsagon/api.py
> +        return self
__enter__ must be defined to use the context, but the return value is unused. I can make it None

2023-06-23 16:13 UTC, montaguegabe commented on src/parsagon/api.py
> +            if isinstance(error_value, dict) and error_value.get("detail") == "Not found.":
Done

2023-06-23 16:13 UTC, montaguegabe commented on src/parsagon/api.py
> +        return self
Done

2023-06-26 21:25 UTC, Sand1929 requested changes

2023-06-26 21:25 UTC, Sand1929 commented on src/parsagon/tests/api_mocks.py
> +            "parsagon.api.httpx.%s" % method,
Are we concerned about making the mock target not editable? e.g., if we imported httpx elsewhere, or if we changed `import httpx` to `from httpx import post` or anything like that, this target will be incorrect

2023-06-28 15:52 UTC, montaguegabe commented on src/parsagon/tests/api_mocks.py
> +            "parsagon.api.httpx.%s" % method,
Yah - that's always the problem with installing mocks in general is the messiness of having to keep track of exactly how and where things are imported.  If we changed the way it's imported then we'd have to add lines that have `mocker.patch("parsagon.api.post", ...)`, or else if httpx is used elsewhere we have to add those places too. I'm not sure of a way around this.  I can add a comment though that says something like `# NOTE: Remember to update this if we add other calling points to the backend, or if we change the way httpx method functions are imported.`

2023-06-28 17:07 UTC, montaguegabe commented
Rebased

2023-06-28 20:17 UTC, montaguegabe commented
Just added new way of accessing API key and API base to prevent them from being used with pytest

2023-06-28 20:30 UTC, Sand1929 approved these changes

2023-06-28 23:55 UTC, merged